### ISSUE TITLE
SF 2.5+ compatibility

### ISSUE THREAD

**Issue by Elexy** [liip/LiipFunctionalTestBundle#177]
i just upgraded to symfony 2.7@stable and now see this:
```
Deprecated: The Liip\FunctionalTestBundle\Validator\DataCollectingValidator class implements Symfony\Component\Validator\MetadataFactoryInterface that is deprecated since version 2.5, to be removed in 3.0. Use {@link Mapping\Factory\MetadataFactoryInterface} instead. in /Users/*****/dev/cb_api/vendor/symfony/symfony/src/Symfony/Component/Debug/DebugClassLoader.php on line 208
```

**Comment by lsmith77** [comment]
I would be happy to merge a PR to fix this .. however for now we have to keep 2.3 compatibility. so it might require adding a small BC hack.

**Comment by alexislefebvre** [comment]
Symfony 2.7 has Long Term Support like Symfony 2.3 have. Can't you force users to upgrade to Symfony 2.7 by requiring Symfony ≥ 2.7 ? The upgrade from 2.3 to 2.7 can be done easily, it was developed while keeping ascending compatbility.

Otherwise, can't you create a new branch specific to Symfony ≥ 2.7? It would be available in Composer in parallel to the current 2.3-compatible master branch.

**Comment by lsmith77** [comment]
since its hard enough to find the time to maintain this Bundle, I would like to wait with dropping 2.3 support until when 2.3 stops getting bug fix releases, which is May 2016

**Comment by alexislefebvre** [comment]
@lsmith77 I understand, thanks for your answer.

**Comment by lakhman** [comment]
+1 - this is annoying, updating the validator version like on this fork didn't seem to help, any ideas how I can fix it on my own fork?

https://github.com/hhamon/LiipFunctionalTestBundle/commit/c6f3c35493c95d8c5d890795b60287e04f0fe48b

**Comment by lsmith77** [comment]
I think the issue is now solved.

**Comment by lakhman** [comment]
I've updated to `dev-master` and `dev-master#b5e90734c54d5b28bedd5830439eda3096b9e878`. I'm still seeing the deprecated error, am I doing something wrong?

`composer.json`:
```
   "liip/functional-test-bundle": "dev-master#b5e90734c54d5b28bedd5830439eda3096b9e878",
```

> The Liip\FunctionalTestBundle\Validator\DataCollectingValidator class implements Symfony\Component\Validator\MetadataFactoryInterface that is deprecated since version 2.5, to be removed in 3.0. Use {@link Mapping\Factory\MetadataFactoryInterface} instead.

**Comment by lsmith77** [comment]
I do not see how this can happen given that the class doesn't extend from another class nor does it implement the interface ``MetadataFactoryInterface``:
https://github.com/liip/LiipFunctionalTestBundle/blob/master/Validator/DataCollectingValidator.php#L21

**Comment by lakhman** [comment]
yeah I see what you mean, I'm currently at symfony `2.8.*`, I'll try moving to `3.0` if I can and see what happens.

**Comment by jmclean** [comment]
`DataCollectingValidator` implements Symfony's `ValidatorInterface`, which inherits from the non-deprecated version of `MetadataFactoryInterface`, which inherits from the deprecated version of `MetadataFactoryInterface`. Thus the deprecation warning is coming from Symfony's *own* use of a deprecated interface. I don't think there's much we can do here. Fortunately the problem goes away in 3.0 because that gets rid of the deprecated base interface entirely.
